---
- name: Deploy nginx using Docker
  hosts: docker_host
  gather_facts: false
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.service:
        name: docker
        state: started
      become: true

    - name: Ensure python3-docker is installed
      apt:
        name: python3-docker
        state: present
      become: true

    - name: Pull nginx image
      community.docker.docker_image:
        name: nginx:latest
        source: pull

    - name: Run nginx container
      community.docker.docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
        restart_policy: unless-stopped

    - name: Wait for port 80 to become available
      ansible.builtin.wait_for:
        port: 80
        delay: 10