---
- name: Deploy Portainer using Docker Compose
  hosts: docker_host
  gather_facts: false
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.service:
        name: docker
        state: started

    - name: Clone GitHub repository
      ansible.builtin.git:
        repo: https://github.com/galjabari/cloud-computing.git
        dest: ~/src

    - name: Run docker compose down
      community.docker.docker_compose_v2:
        project_src: ~/src/portainer 
        state: absent

    - name: Run docker compose up
      community.docker.docker_compose_v2:
        project_src: ~/src/portainer 
        state: present

    - name: Wait for port 9443 to become available
      ansible.builtin.wait_for:
        port: 9443
        delay: 10
