---
- name: Deploy MariaDB using Docker
  hosts: docker_host
  gather_facts: false
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.service:
        name: docker
        state: started

    - name: Ensure Docker SDK for Python is installed
      ansible.builtin.apt:
        name: python3-docker
        state: present
        update_cache: yes
      become: yes

    - name: Pull MariaDB image
      community.docker.docker_image:
        name: mariadb:latest
        source: pull

    - name: Pull phpMyAdmin image
      community.docker.docker_image:
        name: phpmyadmin:latest
        source: pull

    - name: Create virtual network
      docker_network:
        name: db_network

    - name: Run MariaDB container
      community.docker.docker_container:
        name: db
        image: mariadb:latest
        state: started
        restart_policy: always
        env:
          MARIADB_ROOT_PASSWORD: secret
        networks:
          - name: db_network

    - name: Run phpMyAdmin container
      community.docker.docker_container:
        name: phpmyadmin
        image: phpmyadmin:latest
        state: started
        ports:
          - 8080:80        
        restart_policy: always
        env:
          PMA_HOST: db
        networks:
          - name: db_network

    - name: Wait for port 8080 to become available
      ansible.builtin.wait_for:
        port: 8080
        delay: 10