---
- name: Destroy emby Docker container
  hosts: emby_host
  gather_facts: false
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.service:
        name: docker
        state: started
      become: true

    - name: Stop emby container
      community.docker.docker_container:
        name: emby
        state: stopped

    - name: Remove emby container
      community.docker.docker_container:
        name: emby
        state: absent

    - name: Remove emby image
      community.docker.docker_image:
        name: emby/embyserver
        state: absent
        tag: latest
