---
- name: Install Apache on Ubuntu
  hosts: webservers
  gather_facts: false
  become: yes # Run tasks with root privileges
  tasks:
    - name: Update repositories cache and install apache2
      ansible.builtin.apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: Start and enable apache2 service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
