---
- name: Upgrade nginx Docker container
  hosts: docker_host
  gather_facts: false
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.service:
        name: docker
        state: started
      become: true

    - name: Ensure Docker SDK for Python is installed
      ansible.builtin.apt:
        name: python3-docker
        state: present
        update_cache: yes
      become: yes

    - name: Pull latest version of nginx image
      community.docker.docker_image:
        name: nginx:latest
        source: pull

    - name: Stop existing nginx container
      community.docker.docker_container:
        name: nginx
        state: stopped

    - name: Remove existing nginx container
      community.docker.docker_container:
        name: nginx
        state: absent

    - name: Remove existing nginx image
      community.docker.docker_image:
        name: nginx
        state: absent
        tag: latest

    - name: Run new nginx container
      community.docker.docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
        restart_policy: unless-stopped

    - name: Wait for port 80 to become available
      ansible.builtin.wait_for:
        port: 80
        delay: 10