---
- name: Configure Arista cEOS Router 1
  hosts: clab-ospf-router1
  vars:
    ansible_connection: network_cli
    ansible_network_os: arista.eos.eos
    ansible_host_key_checking: false
    ansible_become: yes
  gather_facts: false
  tasks:
    - name: Configure Ethernet interfaces
      arista.eos.eos_l3_interfaces:
        config:
          - name: Ethernet1
            ipv4:
              - address: 192.168.1.1/30
          - name: Ethernet2
            ipv4:
              - address: 192.168.1.5/30
          - name: Loopback0
            ipv4:
              - address: 10.10.10.1/32              
        state: merged
    - name: Enable Ethernet interfaces
      arista.eos.eos_interfaces:
        config:
          - name: Ethernet1
            enabled: true
            mode: layer3
          - name: Ethernet2
            enabled: true
            mode: layer3            
        state: merged
    - name: Enable IP routing
      arista.eos.eos_config:
        lines:
          - ip routing
      
    - name: Configure OSPF settings
      arista.eos.eos_ospfv2:
        config:
          processes:
            - process_id: 1
              router_id: "10.10.10.1"
              networks:
                - prefix: "10.10.10.1/32"
                  area: "0.0.0.0"
                - prefix: "192.168.1.0/30"
                  area: "0.0.0.0"
                - prefix: "192.168.1.4/30"
                  area: "0.0.0.0"                           
        state: merged